### PR TITLE
expose "local_git" feature

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0835da6 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0835da6 with merge 0835da6...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/homu-on-heroku/builds/126782358)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8163a3c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8163a3c with merge 8163a3c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/homu-on-heroku/builds/126783060)

**Pull request merged**
